export const DUMMY_RESOURCES = [
  {
    _id: '1',
    title: 'Data Structures & Algorithms Notes',
    description: 'Complete notes covering arrays, linked lists, trees, graphs, sorting and searching algorithms.',
    subject: 'Data Structures',
    department: 'Computer Science',
    category: 'Notes',
    uploadedBy: { _id: 'u1', name: 'Rahul Sharma' },
    downloads: 342,
    ratings: [{ value: 5 }, { value: 4 }, { value: 5 }, { value: 4 }],
    comments: [
      { name: 'Priya', text: 'Very helpful notes, thanks!' },
      { name: 'Amit', text: 'Covers everything for the exam.' },
    ],
    referenceLinks: ['https://youtube.com/watch?v=abc123', 'https://geeksforgeeks.org/data-structures/'],
    createdAt: '2024-11-10',
  },
  {
    _id: '2',
    title: 'Operating Systems Previous Year Papers',
    description: '5 years of OS question papers with solutions. Covers scheduling, memory management, deadlocks.',
    subject: 'Operating Systems',
    department: 'Computer Science',
    category: 'Question Paper',
    uploadedBy: { _id: 'u2', name: 'Sneha Patel' },
    downloads: 215,
    ratings: [{ value: 5 }, { value: 5 }, { value: 4 }],
    comments: [{ name: 'Karan', text: 'Exactly what I needed before exams!' }],
    createdAt: '2024-11-15',
  },
  {
    _id: '3',
    title: 'Digital Electronics Assignment Unit 3',
    description: 'Solved assignment on combinational circuits, flip-flops and counters.',
    subject: 'Digital Electronics',
    department: 'Electronics',
    category: 'Assignment',
    uploadedBy: { _id: 'u3', name: 'Anjali Mehta' },
    downloads: 128,
    ratings: [{ value: 4 }, { value: 3 }, { value: 4 }],
    comments: [],
    createdAt: '2024-11-20',
  },
  {
    _id: '4',
    title: 'Engineering Mathematics Reference Book',
    description: 'Comprehensive reference for Calculus, Linear Algebra, Differential Equations and Transforms.',
    subject: 'Engineering Mathematics',
    department: 'Mathematics',
    category: 'Reference',
    uploadedBy: { _id: 'u1', name: 'Rahul Sharma' },
    downloads: 489,
    ratings: [{ value: 5 }, { value: 5 }, { value: 5 }, { value: 4 }, { value: 5 }],
    comments: [{ name: 'Neha', text: 'Best reference for maths!' }],
    createdAt: '2024-10-05',
  },
  {
    _id: '5',
    title: 'Thermodynamics Complete Notes',
    description: 'Unit-wise notes for all 5 units. Includes solved examples and important formulas.',
    subject: 'Thermodynamics',
    department: 'Mechanical',
    category: 'Notes',
    uploadedBy: { _id: 'u4', name: 'Vikram Singh' },
    downloads: 176,
    ratings: [{ value: 4 }, { value: 4 }, { value: 5 }],
    comments: [{ name: 'Ravi', text: 'Great notes, very well organized.' }],
    createdAt: '2024-11-01',
  },
  {
    _id: '6',
    title: 'DBMS Lab Assignment Solutions',
    description: 'All 10 lab assignments with SQL queries, ER diagrams and normalization problems solved.',
    subject: 'Database Management Systems',
    department: 'Computer Science',
    category: 'Assignment',
    uploadedBy: { _id: 'u2', name: 'Sneha Patel' },
    downloads: 263,
    ratings: [{ value: 5 }, { value: 4 }, { value: 5 }],
    comments: [{ name: 'Pooja', text: 'Saved my lab submission!' }],
    createdAt: '2024-11-18',
  },
  {
    _id: '7',
    title: 'Structural Analysis Question Bank',
    description: 'Chapter-wise question bank with answers for Structural Analysis. Useful for university exams.',
    subject: 'Structural Analysis',
    department: 'Civil',
    category: 'Question Paper',
    uploadedBy: { _id: 'u5', name: 'Meera Joshi' },
    downloads: 94,
    ratings: [{ value: 3 }, { value: 4 }],
    comments: [],
    createdAt: '2024-11-22',
  },
  {
    _id: '8',
    title: 'Business Management & Marketing Notes',
    description: 'Short and crisp notes for Business Management covering all modules for semester exam.',
    subject: 'Business Management',
    department: 'Business',
    category: 'Notes',
    uploadedBy: { _id: 'u3', name: 'Anjali Mehta' },
    downloads: 157,
    ratings: [{ value: 4 }, { value: 4 }, { value: 3 }, { value: 5 }],
    comments: [{ name: 'Siddharth', text: 'Very concise and helpful.' }],
    createdAt: '2024-11-08',
  },
];

export const DEPARTMENTS = ['Computer Science', 'Electronics', 'Mechanical', 'Civil', 'Business', 'Mathematics', 'Physics'];
export const CATEGORIES = ['Notes', 'Assignment', 'Question Paper', 'Reference'];
export const SEMESTERS = ['Semester 1', 'Semester 2', 'Semester 3', 'Semester 4', 'Semester 5', 'Semester 6', 'Semester 7', 'Semester 8'];
